apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clip-bot
  template:
    metadata:
      labels:
        app: clip-bot
    spec:
      containers:
      - name: clip-bot
        image: senkosanbroentername/clip-bot:newversion
        