name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: senkosanbroentername
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t senkosanbroentername/clip-bot:newversion .
      - name: Push Docker Image
        run: |
          docker push senkosanbroentername/clip-bot:newversion
      - name: Pull Docker Image and Run Container
        run: |
          docker pull senkosanbroentername/clip-bot:newversion
          docker run -d --workdir /app \
            --name clip-bot \
            --restart unless-stopped \
            -e DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" \
            senkosanbroentername/clip-bot:newversion
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
