name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Docker login step
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: senkosanbroentername
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      # Run the Docker container and execute start.py
      - name: Run Docker container
        run: |
              docker build -t senkosanbroentername/clip-bot:newversion .
              docker push senkosanbroentername/clip-bot:newversion
              kubectl rollout restart deployment clip-bot
              kubectl get pods -w")
              docker pull senkosanbroentername/clip-bot:newversion
              docker run --workdir /app senkosanbroentername/clip-bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
