name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: senkosanbroentername
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clean up Docker images and volumes
        run: |
          # Remove unused Docker images
          docker image prune -f
          # Remove unused Docker volumes
          docker volume prune -f

      - name: Build Docker Image
        run: |
          docker build -t senkosanbroentername/clip-bot:newversion .

      - name: Push Docker Image
        run: |
          docker push senkosanbroentername/clip-bot:newversion

      - name: Pull Docker Image and Run Container
        run: |
               docker pull senkosanbroentername/clip-bot:newversion
               nohup docker run -d --workdir /app \
                          --name clip-bot \
                          --restart unless-stopped \
                          --memory=1g --cpus=2 \
                          --health-cmd="curl --fail http://localhost:port/healthcheck || exit 1" \
                          --health-interval=30s \
                          --health-timeout=10s \
                          --health-retries=3 \
                          -e DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" \
                          senkosanbroentername/clip-bot:newversion

        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
